name: Bug investigation
description: |
  If something isn't working as expected.
  (Status codes below 500 are usually a user error and not a server error. i.e. Usually not a bug. Please search existing issues and milestones first.)
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill this out.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the problem and how to reproduce it. Add screenshots or a link to your repository if helpful.
      placeholder: Start typing here.
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What did you expect to happen?
      description: Describe what you expected to happen instead.
      placeholder: Continue typing here.
    validations:
      required: true
  - type: textarea
    id: solutions-tried
    attributes:
      label: What the problem might be?
      description: If you have an idea where the bug might lie, please share here.
